artplatform/blueprints/poster.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from ..models.model import Post
from ..database import database as db

poster = Blueprint("poster", __name__)


@poster.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        img_url = request.form['img_url']
        video_url = request.form['video_url']
        user_id = current_user.id
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            new_post = Post(title=title, description=description, image_url=img_url, video_url=video_url, audio_url=audio_url, user_id=user_id)
            db.session.add(new_post)
            db.session.commit()

            return redirect(url_for('profile'))

    return render_template('poster/create.html')


# def get_post(id, check_author=True):
#     post = get_db().execute(
#         'SELECT p.id, title, body, created, author_id, username'
#         ' FROM post p JOIN user u ON p.author_id = u.id'
#         ' WHERE p.id = ?',
#         (id,)
#     ).fetchone()
#
#     if post is None:
#         abort(404, f"Post id {id} doesn't exist.")
#
#     if check_author and post['author_id'] != g.user['id']:
#         abort(403)
#
#     return post


@poster.route('/<int:post_id>/update', methods=('GET', 'POST'))
@login_required
def update(post_id):
    the_post = Post.query.get_or_404(post_id, "Post not found.")
    if the_post:
        if request.method == 'POST':
            request_title = request.form['title']
            request_description = request.form['description']
            request_image_url = request.form['img_url']
            request_video_url = request.form['video_url']
            request_audio_url = request.form['audio_url']
            error = None
            if not request_title:
                error = 'Title is required.'

            if error is not None:
                flash(error)
            else:
                the_post.title = request_title
                the_post.description = request_description
                the_post.image_url = request_image_url
                the_post.video_url = request_video_url
                the_post.audio_url = request_audio_url
                db.session.commit()
                return redirect(url_for('profile'))

    return render_template('poster/update.html', post=the_post)


@poster.route('/<int:post_id>/delete', methods=('POST',))
@login_required
def delete(post_id):
    the_post = Post.query.get_or_404(post_id, "Post not found.")
    if the_post:
        db.session.delete(the_post)
        db.session.commit()
    return redirect(url_for('profile'))

artplatform/templates/poster/create.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
    <section class="w3-container">
        <form method="post">
            <label for="title">Title</label>
            <input name="title" id="title" value="{{ request.form['title'] }}" required>
            <label for="description">Description</label>
            <textarea name="description" id="description">{{ request.form['description'] }}</textarea>
            <label for="img_url">img_url</label>
            <textarea name="img_url" id="img_url">{{ request.form['img_url'] }}</textarea>
            <label for="video_url">video_url</label>
            <textarea name="video_url" id="video_url">{{ request.form['video_url'] }}</textarea>
            <input type="submit" value="Save">
        </form>
    </section>
{% endblock %}

artplatform/templates/poster/update.html
{% extends 'base.html' %}

{% block header %}
    <h1>{% block title %}Edit "{{ post['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        <label for="title">Title</label>
        <input name="title" id="title"
               value="{{ request.form['title'] or post['title'] }}" required>
        <label for="description">Description</label>
        <textarea name="description"
                  id="description">{{ request.form['description'] or post['description'] }}</textarea>
        <label for="img_url">img_url</label>
        <textarea name="img_url" id="img_url">{{ request.form['image_url'] or post['image_url'] }}</textarea>
        <label for="video_url">video_url</label>
        <textarea name="video_url" id="video_url">{{ request.form['video_url'] or post['video_url'] }}</textarea>
        <label for="audio_url">audio_url</label>
        <textarea name="audio_url" id="audio_url">{{ request.form['audio_url'] or post['audio_url'] }}</textarea>
        <input type="submit" value="Save">
    </form>
    <hr>
    <form action="{{ url_for('poster.delete', post_id=post['id']) }}" method="post">
        <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
    </form>
{% endblock %}