artplatform/blueprints/auth.py
from flask import Blueprint, redirect, render_template, url_for, request, flash
from flask_login import login_user, login_required, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
from ..models.model import UserLogin
from ..database import database as db

auth = Blueprint('auth', __name__)


# check this link for help:
# https://www.digitalocean.com/community/tutorials/how-to-add-authentication-to-your-app-with-flask-login

@auth.route('/login')
def login():
    return render_template("auth/login.html")


@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form['email']
    password = request.form['password']
    remember = True if request.form.get('remember') else False
    user = UserLogin.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))  # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('profile'))


@auth.route('/register')
def register():
    return render_template("auth/register.html")


@auth.route('/register', methods=['POST'])
def register_post():
    email = request.form['email']
    name = request.form['name']
    password = request.form['password']
    error = None

    user = UserLogin.query.filter_by(email=email).first()

    if not email:
        error = 'E-mail is required.'
    elif not name:
        error = 'Name is required.'
    elif not password:
        error = 'Password is required.'
    elif user:
        error = f'User {name} with E-mail address {email} is already registered.'

    # create a new user with the form data. Hash the password so the plaintext version isn't saved.
    if error is None:
        new_user = UserLogin(email=email, name=name, password=generate_password_hash(password, method='sha256'))

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('auth.login'))

    flash(error)
    return redirect(url_for("auth.register"))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

artplatform/blueprints/poster.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from ..models.model import Post
from ..database import database as db

poster = Blueprint("poster", __name__)


@poster.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        img_url = request.form['img_url']
        video_url = request.form['video_url']
        user_id = current_user.id
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            new_post = Post(title=title, description=description, image_url=img_url, video_url=video_url, audio_url=audio_url, user_id=user_id)
            db.session.add(new_post)
            db.session.commit()

            return redirect(url_for('profile'))

    return render_template('poster/create.html')


# def get_post(id, check_author=True):
#     post = get_db().execute(
#         'SELECT p.id, title, body, created, author_id, username'
#         ' FROM post p JOIN user u ON p.author_id = u.id'
#         ' WHERE p.id = ?',
#         (id,)
#     ).fetchone()
#
#     if post is None:
#         abort(404, f"Post id {id} doesn't exist.")
#
#     if check_author and post['author_id'] != g.user['id']:
#         abort(403)
#
#     return post


@poster.route('/<int:post_id>/update', methods=('GET', 'POST'))
@login_required
def update(post_id):
    the_post = Post.query.get_or_404(post_id, "Post not found.")
    if the_post:
        if request.method == 'POST':
            request_title = request.form['title']
            request_description = request.form['description']
            request_image_url = request.form['img_url']
            request_video_url = request.form['video_url']
            request_audio_url = request.form['audio_url']
            error = None
            if not request_title:
                error = 'Title is required.'

            if error is not None:
                flash(error)
            else:
                the_post.title = request_title
                the_post.description = request_description
                the_post.image_url = request_image_url
                the_post.video_url = request_video_url
                the_post.audio_url = request_audio_url
                db.session.commit()
                return redirect(url_for('profile'))

    return render_template('poster/update.html', post=the_post)


@poster.route('/<int:post_id>/delete', methods=('POST',))
@login_required
def delete(post_id):
    the_post = Post.query.get_or_404(post_id, "Post not found.")
    if the_post:
        db.session.delete(the_post)
        db.session.commit()
    return redirect(url_for('profile'))

artplatform/blueprints/posts.py
from flask import Blueprint, request, render_template, redirect, url_for, abort
from flask_login import current_user
from ..database import database
from ..models.model import Post

posts = Blueprint("posts", __name__, url_prefix="/posts")


@posts.route("/", methods=["GET", "POST"])
def all():
    if request.method == "POST":
        database.session.add(Post(
            title=request.form["post_title"],
            image_url=request.form["image_url"],
            description=request.form["post_description"],
            video_url=request.form["video_url"], #
            audio_url=request.form["audio_url"], #
            user_id=current_user.id
        ))
        database.session.commit()
    all_posts = Post.query.all()
    return render_template("posts.html", posts=all_posts)


@posts.route("/<post_id>", methods=["GET", "POST"])
def single(post_id):
    the_post = Post.query.get_or_404(post_id, "Post not found.")
    if the_post:
        if request.method == "POST":
            if request.form["submit_button"] == "delete":
                database.session.delete(the_post)
                database.session.commit()
                return redirect(url_for("posts.all"))
            if request.form["submit_button"] == "put":
                the_post.title = request.form["post_title"]
                the_post.description = request.form["post_description"]
                the_post.image_url = request.form["image_url"]
                the_post.video_url = request.form["video_url"] #
                the_post.audio_url = request.form["audio_url"] #
                the_post.done = "completed" in request.form
                database.session.commit()
        return render_template("post.html", post=the_post)

artplatform/blueprints/profile.py
from flask import Blueprint, request, render_template, redirect, url_for, abort
from flask_login import current_user
from ..database import database
from ..models.model import Post
from werkzeug import secure_filename
from flask import Flask, render_template, request, redirect, url_for

@app.route('/')
def introduction():
    return render_template('profile.html')

@app.route('/', methods=['POST'])
def introduction_post():
    text = request.form['text']
    processed_text = text.upper()
    return processed_text

artplatform/templates/Gallery.html
<!DOCTYPE html>
<html lang="en-us">

<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>ArtViewer</title>
  <link rel="shortcut icon" href="static/TemplateData/favicon.ico">
  <link rel="stylesheet" href="static/TemplateData/style.css">
</head>

<body>
  <div id="unity-container" class="unity-desktop">
    <canvas id="unity-canvas" width=960 height=600></canvas>
    <div id="unity-loading-bar">
      <div id="unity-logo"></div>
      <div id="unity-progress-bar-empty">
        <div id="unity-progress-bar-full"></div>
      </div>
    </div>
    <div id="unity-mobile-warning">
      WebGL builds are not supported on mobile devices.
    </div>
    <div id="unity-footer">
      <div id="unity-fullscreen-button"></div>
      <div id="unity-build-title">ArtViewer</div>
      <div>
				<p>
					Move: WASD/UDLR<br/>
					Look: MOUSE
				</p>
			</div>
    </div>
  </div>
  <script>
    var buildUrl = "static/Build";
    var loaderUrl = buildUrl + "/project2.loader.js";
    var config = {
      dataUrl: buildUrl + "/project2.data",
      frameworkUrl: buildUrl + "/project2.framework.js",
      codeUrl: buildUrl + "/project2.wasm",
      streamingAssetsUrl: "static/StreamingAssets",
      companyName: "DefaultCompany",
      productName: "ArtViewer",
      productVersion: "0.1",
    };

    var container = document.querySelector("#unity-container");
    var canvas = document.querySelector("#unity-canvas");
    var loadingBar = document.querySelector("#unity-loading-bar");
    var progressBarFull = document.querySelector("#unity-progress-bar-full");
    var fullscreenButton = document.querySelector("#unity-fullscreen-button");
    var mobileWarning = document.querySelector("#unity-mobile-warning");

    // By default Unity keeps WebGL canvas render target size matched with
    // the DOM size of the canvas element (scaled by window.devicePixelRatio)
    // Set this to false if you want to decouple this synchronization from
    // happening inside the engine, and you would instead like to size up
    // the canvas DOM size and WebGL render target sizes yourself.
    // config.matchWebGLToCanvasSize = false;

    if (/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)) {
      container.className = "unity-mobile";
      // Avoid draining fillrate performance on mobile devices,
      // and default/override low DPI mode on mobile browsers.
      config.devicePixelRatio = 1;
      mobileWarning.style.display = "block";
      setTimeout(() => {
        mobileWarning.style.display = "none";
      }, 5000);
    } else {
      canvas.style.width = "960px";
      canvas.style.height = "600px";
    }
    loadingBar.style.display = "block";

    var script = document.createElement("script");
    script.src = loaderUrl;
    script.onload = () => {
      createUnityInstance(canvas, config, (progress) => {
        progressBarFull.style.width = 100 * progress + "%";
      }).then((unityInstance) => {
        loadingBar.style.display = "none";
        fullscreenButton.onclick = () => {
          unityInstance.SetFullscreen(1);
        };
      }).catch((message) => {
        alert(message);
      });
    };
    document.body.appendChild(script);
  </script>
</body>

</html>

artplatform/templates/base.html
<!doctype html>
<style>
    html, body {
        margin: 0;
        min-height: 100vh;
    }

    header {
        background-color: #666;
        padding: 30px;
        text-align: center;
        font-size: 35px;
        color: white;
        opacity: 0.8;
    }

    nav {
        min-height: 100vh;
        float: left;
        width: 10%;
        background: #ccc;
        padding: 20px;
        opacity: 0.6;

    }

    /* Style the list inside the menu */
    nav ul {
        list-style-type: square;
        padding: 10px;

    }

    article {
        float: left;
        width: 90%;
        padding: 200px;
        text-align: center;
        background-color: white;
    }

    /* Clear floats after the columns */
    .clearfix::after {
        content: "";
        display: table;
        clear: both;

    }

    /* Style the footer */
    footer {
        background-color: #777;
        padding: 10px;
        text-align: center;
        color: white;
        opacity: 0.8;

    }

    {% block style %}{% endblock %}
</style>
<html lang="en">
<head>

    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="../static/css/post.css">
    <link rel="stylesheet" href="../static/css/w3.css">

    <style>html, body, h1, h2, h3, h4, h5 {
        font-family: "Raleway", sans-serif
    }

    </style>

    <title>
        ArtView
    </title>
</head>

<header>
    <h1>ArtView</h1>
</header>

<body>


<div id="main" class="w3-main w3-display-container">
    <! -- Flash messages -->
    <div class="w3-container w3-animate-opacity">
        {% for message in get_flashed_messages() %}
            <div class="w3-panel
											w3-pale-green
											w3-leftbar
											w3-border-green
											w3-animate-right
											w3-display-content">
                {{ message }}
            </div>
        {% endfor %}
    </div>
</div>

<div class="clearfix">
    <nav>
        <ul>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('profile') }}" class="w3-container">
                    Profile
                </a>
                <a href="{{ url_for('auth.logout') }}" class="w3-container">
                    Logout
                </a>
                <a href="{{ url_for("posts.all") }}" class="w3-container">
                    Artworks
                </a>
                <a href="{{ url_for('threeD') }}" class="w3-container">
                    3D demo
                </a>
                <a href="{{ url_for('gallery') }}" class="w3-container">
                    new Gallery
                </a>
            {% endif %}
            {% if not current_user.is_authenticated %}
                <a href="{{ url_for('auth.login') }}" class="w3-container">
                    Login
                </a>
                <a href="{{ url_for('auth.register') }}" class="w3-container">
                    Sign Up
                </a>
                <a href="{{ url_for('viewerEntrance') }}" class="w3-container">
                    Viewer Entrance
                </a>
            {% endif %}
            <!-- <a href="{{ url_for('threeD') }}" class="w3-container">
                3D demo
            </a>
            <a href="{{ url_for('gallery') }}" class="w3-container">
                new Gallery
            </a> -->
        </ul>
        {% block header %}{% endblock %}
    </nav>

    <article>
        {% block content %}
        {% endblock %}
    </article>
</div>
{% block scripts %}{% endblock %}
<script type="text/javascript" color="0,205,205" opacity='0.8' zIndex="-1" count="200"
        src="//cdn.bootcss.com/canvas-nest.js/1.0.1/canvas-nest.min.js"></script>
</body>

<footer>
    <a href="{{ url_for('index') }}">Back to Index Page</a>
</footer>
</html>

artplatform/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div>
            <h1>Image Platform Designed for Artists</h1>
            <p>
                <!-- Go <a href="{{ url_for("posts.all") }}">here</a> to
                see all the artworks uploaded. -->
                {% if current_user.is_authenticated %}
                    Go <a href="{{ url_for("posts.all") }}">here</a> to
                                    see all the artworks uploaded.
                {% endif %}
                {% if not current_user.is_authenticated %}
                    Please sign up/log in first.
                {% endif %}
            </p>
    </div>
{% endblock content %}

artplatform/templates/posts.html
{% extends "base.html" %}

{% block content %}

    <div class="w3-content">
        <div class="w3-margin">
            <div id="new-post" style="display:none">
                <form action="{{ url_for("posts.all") }}" method="POST"
                      class="w3-container w3-card w3-padding w3-margin">
                    <h3>New post</h3>
                    <hr>
                    <p>
                        <input class="w3-input" name="post_title" type="text" placeholder="Title">
                    </p>
                    <p>
                        <textarea class="w3-input" name="post_description" type="textarea"
                                  placeholder="Description"></textarea>
                    </p>
                    <p>
                        <input class="w3-input" name="image_url" type="text" placeholder="Image_URL">
                    </p>
                    <p>
                        <input class="w3-input" name="video_url" type="text" placeholder="Video_URL">
                    </p>
                    <p>
                        <input class="w3-input" name="audio_url" type="text" placeholder="Audio_URL">
                    </p>
                    <button
                            type="submit"
                            class="w3-right w3-button w3-large
                   w3-white w3-border w3-text-indigo
                   w3-hover-indigo w3-round w3-margin">
                        Add
                    </button>
                </form>
            </div>
            {% if current_user.is_authenticated %}
            <button
                    id="add-post"
                    class="w3-right w3-button w3-large
                 w3-white w3-border w3-text-indigo
                 w3-hover-indigo w3-round w3-margin">
                New
            </button>
            {% endif %}
            <div class="w3-container">
                <ul class="w3-ul w3-card">
                    {% for post in posts %}
                        <li class="w3-large">
                            <a href="{{ url_for("posts.single", post_id=post["id"]) }}"
                               style="display:block; text-decoration:none ">{{ post["title"] }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script
            charset="utf-8"
            type="text/javascript"
            src="{{ url_for('static', filename='js/posts.js') }}">
    </script>
{% endblock scripts %}

artplatform/templates/profile.html
{% extends "base.html" %}

{% block header %}
    
    <!-- {% if current_user.is_authenticated %}
        <a class="action" href="{{ url_for('poster.create') }}">
            <button 
            class="w3-bar-item w3-button w3-large
            w3-white w3-border w3-text-indigo
            w3-hover-indigo w3-round w3-left"
            >New</button></a>
    {% endif %} -->
{% endblock %}

{% block content %}
    <body>
        <h1>My Profile: About me</h1>
        <p>
            © 2020 by Evelyn Chow
        </p>

        <!-- <h1>File Upload</h1>
        <form method="POST" action="" enctype="multipart/form-data">
            <p><input type="file" name="file"></p>
            <p><input type="submit" value="Submit"></p>
        </form> -->
        
            <!-- <form method="POST">
                <input name="text">
                <input type="submit">
            </form> -->
    </body>
    <!-- <button
        id="add-post"
        class="w3-right w3-button w3-large
        w3-white w3-border w3-text-indigo
        w3-hover-indigo w3-round w3-margin">
        New
    </button> -->
    
{% endblock %}

{#{% block scripts %}
    <script
        charset="utf-8"
        type="text/javascript"
        src="{{ url_for('static', filename='js/zoomIn.js') }}">
    </script>
{% endblock scripts %}#}

artplatform/templates/viewerEntrance.html
{% extends "base.html" %}

{% block header %}
    
    <!-- {% if current_user.is_authenticated %}
        <a class="action" href="{{ url_for('poster.create') }}">
            <button 
            class="w3-bar-item w3-button w3-large
            w3-white w3-border w3-text-indigo
            w3-hover-indigo w3-round w3-left"
            >New</button></a>
    {% endif %} -->
{% endblock %}

{% block content %}
    <body>
        <ul>
            <a href="{{ url_for('profile') }}" class="w3-container">
                Artist's Profile
            </a>
            <a href="{{ url_for("posts.all") }}" class="w3-container">
                Artworks
            </a>
            <a href="{{ url_for('threeD') }}" class="w3-container">
                3D demo
            </a>
            <a href="{{ url_for('gallery') }}" class="w3-container">
                new Gallery
            </a>
        </ul>

        <!-- <h1>File Upload</h1>
        <form method="POST" action="" enctype="multipart/form-data">
            <p><input type="file" name="file"></p>
            <p><input type="submit" value="Submit"></p>
        </form> -->
        
            <!-- <form method="POST">
                <input name="text">
                <input type="submit">
            </form> -->
    </body>
    <!-- <button
        id="add-post"
        class="w3-right w3-button w3-large
        w3-white w3-border w3-text-indigo
        w3-hover-indigo w3-round w3-margin">
        New
    </button> -->
    
{% endblock %}

{#{% block scripts %}
    <script
        charset="utf-8"
        type="text/javascript"
        src="{{ url_for('static', filename='js/zoomIn.js') }}">
    </script>
{% endblock scripts %}#}